apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-id-api-rust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-id-api-rust
  template:
    metadata:
      labels:
        app: node-id-api-rust
    spec:
      containers:
        - name: node-id-api-rust
          image: node-id-api-rust:latest  # Replace with your image tag if needed
          imagePullPolicy: Never          # Use "IfNotPresent" if needed
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: node-id-api-rust
spec:
  type: LoadBalancer
  selector:
    app: node-id-api-rust
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-id-api-rust-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-id-api-rust
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
